import{useEffect,useMemo,useState}from'react';import{wordSets}from'./words.js';
const groups=Object.keys(wordSets),shuffle=a=>[...a].sort(()=>Math.random()-.5),read=(k,f)=>{try{return localStorage.getItem(k)??f}catch{return f}};
export default function App(){const[group,setGroup]=useState(()=>read('woordjes-group','Groep 6')),[mode,setMode]=useState('leren'),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[done,setDone]=useState(0),[feedback,setFeedback]=useState(null),[stars,setStars]=useState(()=>Number(read('woordjes-stars','0'))),[showMeaning,setShowMeaning]=useState(false),[online,setOnline]=useState(navigator.onLine),[installPrompt,setInstallPrompt]=useState(null);const entries=useMemo(()=>wordSets[group].map(([word,meaning])=>({word,meaning})),[group]),entry=entries[index%entries.length],choices=useMemo(()=>shuffle([entry,...shuffle(entries.filter(x=>x.word!==entry.word)).slice(0,3)]),[entry,entries]);
useEffect(()=>{localStorage.setItem('woordjes-group',group);localStorage.setItem('woordjes-stars',String(stars))},[group,stars]);useEffect(()=>{const a=()=>setOnline(true),b=()=>setOnline(false),c=e=>{e.preventDefault();setInstallPrompt(e)};addEventListener('online',a);addEventListener('offline',b);addEventListener('beforeinstallprompt',c);return()=>{removeEventListener('online',a);removeEventListener('offline',b);removeEventListener('beforeinstallprompt',c)}},[]);
const resetRound=()=>{setAnswer('');setSelected(null);setFeedback(null);setShowMeaning(false)},reset=(g=group)=>{setGroup(g);setIndex(0);setScore(0);setDone(0);resetRound()},next=()=>{setIndex(i=>(i+1)%entries.length);resetRound()},reward=ok=>{setFeedback(ok);setDone(d=>d+1);if(ok){setScore(s=>s+1);setStars(s=>s+1)}},check=()=>{if(answer.trim()&&feedback===null)reward(answer.trim().toLocaleLowerCase('nl-NL')===entry.word.toLocaleLowerCase('nl-NL'))},choose=x=>{if(feedback===null){setSelected(x.word);reward(x.word===entry.word)}},speak=t=>{if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='nl-NL';u.rate=.78;speechSynthesis.speak(u)}},install=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)}},switchMode=m=>{setMode(m);resetRound()};
return <main className="shell"><div className="app"><header><div><small>✨ Leren wordt een avontuur</small><h1>Woordjesavontuur</h1></div><b className="stars">⭐ {stars}</b></header>{!online&&<div className="notice">📴 Je bent offline. Oefenen blijft mogelijk.</div>}{installPrompt&&<button className="install" onClick={install}>📱 Zet de app op mijn telefoon</button>}<div className="layout"><aside><div className="panel"><b>📖 Kies je groep</b><div className="groups">{groups.map(g=><button key={g} className={g===group?'active':''} onClick={()=>reset(g)}>{g.replace('Groep ','G')}</button>)}</div></div><div className="modes"><button className={mode==='leren'?'active':''} onClick={()=>switchMode('leren')}>👁 Leren</button><button className={mode==='betekenis'?'active green':''} onClick={()=>switchMode('betekenis')}>🧠 Betekenis</button><button className={mode==='dictee'?'active purple':''} onClick={()=>switchMode('dictee')}>🔊 Dictee</button></div></aside><section><div className="meta"><span>{group}</span><span>{done} geoefend · {score} goed</span></div><div className="progress"><i style={{width:`${Math.min(100,done/entries.length*100)}%`}}/></div><div className="card">
{mode==='leren'&&<><label>WOORD EN BETEKENIS</label><h2>{entry.word}</h2><button className="listen" onClick={()=>speak(entry.word)}>🔊 Luister</button>{showMeaning?<div className="meaning">{entry.meaning}</div>:<button className="reveal" onClick={()=>setShowMeaning(true)}>Toon betekenis</button>}<button className="primary" onClick={next}>Volgende woord</button></>}
{mode==='betekenis'&&<><label className="greenText">WELKE BETEKENIS HOORT ERBIJ?</label><h2>{entry.word}</h2><div className="choices">{choices.map(x=>{const state=feedback!==null&&x.word===entry.word?'right':selected===x.word?'wrongChoice':'';return <button key={x.word} disabled={feedback!==null} className={state} onClick={()=>choose(x)}>{x.meaning}</button>})}</div>{feedback!==null&&<><div className={feedback?'feedback ok':'feedback no'}>{feedback?'✓ Goed gekozen!':'✕ Dat was niet de juiste betekenis.'}</div><button className="primary greenBg" onClick={next}>Volgende</button></>}</>}
{mode==='dictee'&&<><label>LUISTER EN TYP</label><button className="speaker" onClick={()=>speak(entry.word)}>🔊</button><div className="answer"><input autoCapitalize="none" autoCorrect="off" spellCheck="false" value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(feedback===null?check():next())} placeholder="Typ het woord…"/><button className="primary purpleBg" onClick={feedback===null?check:next}>{feedback===null?'Nakijken':'Verder'}</button></div>{feedback!==null&&<div className={feedback?'feedback ok':'feedback no'}>{feedback?'✓ Super, goed geschreven!':`✕ Bijna! Het woord is ${entry.word}.`}</div>}</>}
</div><button className="reset" onClick={()=>reset()}>↻ Oefening opnieuw</button></section></div></div></main>}
