export const wordSets={
'Groep 3':[['boom','Een grote plant met een stam en takken.'],['vis','Een dier dat in water leeft en met kieuwen ademt.'],['maan','Het hemellichaam dat om de aarde draait.'],['boek','Een verzameling bladzijden met tekst of afbeeldingen.']],
'Groep 4':[['vriend','Iemand met wie je graag omgaat.'],['markt','Een plek waar mensen producten verkopen.'],['verhaal','Een vertelling over gebeurtenissen of personen.'],['wereld','De aarde met alles en iedereen erop.']],
'Groep 5':[['bibliotheek','Een plek waar je boeken kunt lenen en lezen.'],['verschil','Datgene waarin dingen niet hetzelfde zijn.'],['omgeving','Alles wat zich rond een plek of persoon bevindt.'],['antwoord','Wat je zegt of schrijft als reactie op een vraag.']],
'Groep 6':[
['de architectuur','De kunst en manier waarop gebouwen worden ontworpen.'],['authentiek','Echt en oorspronkelijk, niet nagemaakt.'],['berucht','Bekend vanwege iets slechts of vervelends.'],['het dialect','Een taalvorm die in een bepaalde streek wordt gesproken.'],['eeuwenoud','Al vele eeuwen oud.'],['exclusief','Alleen bestemd voor een bepaalde groep, of zonder iets anders.'],['de gevel','De buitenkant aan de voorzijde van een gebouw.'],['de grachtengordel','Een reeks grachten die als een boog om een stadscentrum ligt.'],['hedendaags','Van deze tijd, modern.'],['historisch','Te maken hebbend met het verleden.'],['internationaal','Waar meerdere landen bij betrokken zijn.'],['levendig','Druk, actief en vol beweging.'],['het monument','Een bijzonder bouwwerk dat vanwege zijn waarde wordt beschermd.'],['nationaal','Van of voor een heel land.'],['oorspronkelijk','Zoals iets in het begin was.'],['reserveren','Iets vooraf voor jezelf laten vasthouden.'],['slenteren','Rustig lopen zonder haast en ondertussen rondkijken.'],['statig','Groot, indrukwekkend en deftig.'],['het tarief','Het vaste bedrag dat je voor een dienst betaalt.'],['de aangifte','Een melding bij de politie over een mogelijk strafbaar feit.'],['de afkomst','De plek, familie of groep waar iemand vandaan komt.'],['het appartement','Een woning die deel uitmaakt van een groter gebouw.'],['de bovenwoning','Een woning die boven een andere ruimte of woning ligt.'],['de buitenwijk','Een woongebied aan de rand van een stad.'],['de criminaliteit','Alle strafbare activiteiten in een gebied of periode.'],['de cultuur','Gewoonten, ideeën en gebruiken van een groep mensen.'],['de eengezinswoning','Een huis dat bedoeld is voor een gezin.'],['de galerij','Een gang langs woningen waarop voordeuren uitkomen.'],['de groenvoorziening','Parken, bomen en ander openbaar groen in een gebied.'],['heling','Gestolen spullen kopen, bewaren of verkopen terwijl je dat weet.'],['de hoogbouw','Hoge gebouwen met veel verdiepingen.'],['de leegstand','De situatie waarin gebouwen niet worden gebruikt.'],['massaal','Met heel veel mensen of dingen tegelijk.'],['multicultureel','Met mensen en invloeden uit meerdere culturen.'],['de nationaliteit','Het land waarvan iemand officieel burger is.'],['de overlast','Ernstige of herhaalde hinder.'],['het portiek','Een overdekte ingang van een gebouw.'],['preventief','Bedoeld om een probleem vooraf te voorkomen.'],['rumoerig','Druk en vol lawaai.']],
'Groep 7':[['maatschappij','De samenleving waarin mensen met elkaar leven.'],['conclusie','Een oordeel dat volgt uit informatie of onderzoek.'],['verschijnsel','Iets dat voorkomt en dat je kunt waarnemen.'],['traditie','Een gebruik dat lange tijd wordt doorgegeven.']],
'Groep 8':[['democratie','Een bestuursvorm waarin burgers invloed hebben op besluiten.'],['argument','Een reden waarmee je een mening ondersteunt.'],['perspectief','De manier waarop iemand naar iets kijkt.'],['interpretatie','De betekenis of uitleg die iemand aan iets geeft.']]
}
